name: Microservices CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies + pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 4️⃣ Run Tests (NEW CI STEP ✅)
      - name: Run tests
        run: |
          pytest

      # 5️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to DockerHub (USES YOUR SECRETS)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 4️⃣ Build & Push Gateway Service
      - name: Build and Push Gateway Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway-service ./gateway-service
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service

      # 5️⃣ Build & Push User Service
      - name: Build and Push User Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service

      # 6️⃣ Build & Push Product Service
      - name: Build and Push Product Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service ./product-service
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service

      # 7️⃣ Build & Push Order Service
      - name: Build and Push Order Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service ./order-service
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service



      # 6️⃣ Build Docker Containers
      # - name: Build Containers
      #   run: |
      #     docker compose build